// Renders the bash installer/uninstaller scripts that teammates curl|bash.
// The server URL is baked in at render time so the output is self-contained.
// Keep the scripts pure bash and dependency-free — they run on teammate
// Macs with only system tooling.
//
// Escaping: this is a TS template literal emitting bash. A literal `$` is
// written `\$`; JS `${...}` is reserved for render-time substitutions
// (server URL, LaunchAgent label).

// Legacy launchd label — fielded daemons depend on it; do not rename.
const LABEL = "sh.anara.leaderboard";

function trimTrailingSlash(url: string): string {
  return url.replace(/\/+$/, "");
}

export interface InstallScriptOpts {
  /** Banner subtitle (TOKENLEADER_TEAM_NAME). Display-only; sanitized so it
   *  cannot break the printf format. */
  teamName?: string;
  /** True when TOKENLEADER_JOIN_TOKEN is set: the script advertises
   *  `--join=<code>`. The code itself is NEVER baked in — /install is an
   *  unauthenticated route. */
  joinRequired?: boolean;
}

/** Strip anything that could escape a double-quoted printf format. */
function bashSafe(s: string): string {
  return s.replace(/[^A-Za-z0-9 ._-]/g, "");
}

// Bash preamble shared with the local-clone installer (scripts/install.sh):
// colors, banner, handle resolution, step helpers, verification, summary.
// The baked server URL can be overridden at run time via
// $TOKENLEADER_INSTALL_URL (staging).
function renderSharedBashPreamble(serverUrlLiteral: string, opts: InstallScriptOpts = {}): string {
  const subtitle = opts.teamName
    ? `${bashSafe(opts.teamName)} team token-usage leaderboard`
    : "team token-usage leaderboard";
  const oneLinerJoin = opts.joinRequired ? " -s -- --join=<code>" : "";
  return `#!/usr/bin/env bash
# tokenleader self-serve installer.
# Generated by the tokenleader server at ${serverUrlLiteral}.
# Idempotent: safe to re-run. Installs a per-user LaunchAgent that posts
# token usage events to ${serverUrlLiteral}. The daemon generates its own
# per-user secret on first run (TOFU); no shared credential to copy around.
set -euo pipefail

SERVER_URL="\${TOKENLEADER_INSTALL_URL:-${serverUrlLiteral}}"
LABEL="${LABEL}"
DOMAIN="gui/\$(id -u)"
LOG_DIR="\$HOME/Library/Logs/anara-leaderboard"
STDERR_LOG="\$LOG_DIR/stderr.log"
STDOUT_LOG="\$LOG_DIR/stdout.log"
BIN_DST="\$HOME/.local/bin/anara-leaderboard"
PLIST="\$HOME/Library/LaunchAgents/\${LABEL}.plist"
STATE_DIR="\$HOME/.local/share/anara-leaderboard"
TOTAL_STEPS=5

# --- color setup ----------------------------------------------------------
# Only emit ANSI when stdout is an interactive TTY. curl|bash usually keeps
# stdout pointed at the terminal so colors work; CI pipes get clean text.
if [ -t 1 ]; then
  C_RESET=\$'\\033[0m'
  C_BOLD=\$'\\033[1m'
  C_DIM=\$'\\033[2m'
  C_GREEN=\$'\\033[0;32m'
  C_RED=\$'\\033[0;31m'
  C_YELLOW=\$'\\033[0;33m'
  C_CYAN=\$'\\033[0;36m'
else
  C_RESET=""; C_BOLD=""; C_DIM=""
  C_GREEN=""; C_RED=""; C_YELLOW=""; C_CYAN=""
fi

# --- platform check -------------------------------------------------------
if [ "\$(uname -s)" != "Darwin" ]; then
  printf "%stokenleader only supports macOS. Detected: %s.%s\\n" \\
    "\$C_RED" "\$(uname -s)" "\$C_RESET" >&2
  exit 1
fi

# ARCH_PATH doubles as the /bin asset suffix AND the manifest.json key,
# so Intel maps to "x64" (the manifest's key; the /bin route accepts it).
RAW_ARCH="\$(uname -m)"
case "\$RAW_ARCH" in
  arm64)  ARCH_PATH="arm64"; ARCH_LABEL="Apple Silicon (arm64)" ;;
  x86_64) ARCH_PATH="x64";   ARCH_LABEL="Intel Mac (x86_64)" ;;
  *)
    printf "%sUnsupported arch '%s'. Only arm64 and x86_64.%s\\n" \\
      "\$C_RED" "\$RAW_ARCH" "\$C_RESET" >&2
    exit 1
    ;;
esac

# NO interactive prompts: /dev/tty semantics differ wildly across terminals
# under curl|bash. Sensible defaults + env overrides instead; re-running the
# installer is idempotent.

# --- banner + pre-flight --------------------------------------------------
DIVIDER="\${C_DIM}──────────────────────────────────────────────────────────────────\${C_RESET}"

print_banner() {
  printf "\\n"
  printf "  %stokenleader installer%s\\n" "\$C_BOLD" "\$C_RESET"
  printf "  %s${subtitle}%s\\n" "\$C_DIM" "\$C_RESET"
  printf "\\n"
  printf "  %sendpoint%s    %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
  printf "  %splatform%s    %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$ARCH_LABEL" "\$C_RESET"
  printf "  %shandle%s      %s%s%s  %s(from %s)%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$USER_NAME" "\$C_RESET" \\
    "\$C_DIM" "\$HANDLE_SOURCE" "\$C_RESET"
  printf "  %sinstalling%s  %s~/.local/bin/anara-leaderboard%s  +  %sLaunchAgent%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$C_RESET" "\$C_BOLD" "\$C_RESET"
  printf "\\n"
  printf "  %sto use a different handle, re-run with:%s\\n" "\$C_DIM" "\$C_RESET"
  printf "    %sTOKENLEADER_USER=your-name curl -fsSL %s/install | bash${oneLinerJoin}%s\\n" \\
    "\$C_DIM" "\$SERVER_URL" "\$C_RESET"
  printf "\\n"
  printf "%s\\n" "\$DIVIDER"
  printf "\\n"
}

# --- pick leaderboard handle ----------------------------------------------
# Order: --name flag, TOKENLEADER_USER, \$USER, fallback — always slugified.
slugify() {
  printf '%s' "\$1" \\
    | LC_ALL=C tr '[:upper:]' '[:lower:]' \\
    | LC_ALL=C sed -E 's/[^a-z0-9_-]+/-/g; s/-+/-/g; s/^-+//; s/-+\$//' \\
    | cut -c1-32
}

resolve_handle() {
  local raw="\${ARG_NAME:-}"
  local source="--name"
  if [ -z "\$raw" ]; then
    raw="\${TOKENLEADER_USER:-}"
    source="TOKENLEADER_USER"
  fi
  if [ -z "\$raw" ]; then
    raw="\${USER:-\$(id -un 2>/dev/null || echo)}"
    source="\\\$USER"
  fi
  USER_NAME="\$(slugify "\$raw")"
  if [ -z "\$USER_NAME" ]; then
    USER_NAME="tokenleader-user"
    source="fallback"
  fi
  HANDLE_SOURCE="\$source"
  HANDLE_RAW="\$raw"
}

# --- parse args -----------------------------------------------------------
ARG_NAME=""
ARG_JOIN=""
ARG_COMPANY=""
while [ \$# -gt 0 ]; do
  case "\$1" in
    --name=*)     ARG_NAME="\${1#--name=}" ;;
    --name)       ARG_NAME="\${2:-}"; shift ;;
    --join=*)     ARG_JOIN="\${1#--join=}" ;;
    --join)       ARG_JOIN="\${2:-}"; shift ;;
    --company=*)  ARG_COMPANY="\${1#--company=}" ;;
    --company)    ARG_COMPANY="\${2:-}"; shift ;;
    -h|--help)
      printf "tokenleader installer\\n\\n"
      printf "Usage: curl -fsSL %s/install | bash -s -- [--name=HANDLE] [--join=CODE] [--company=DOMAIN]\\n\\n" "\$SERVER_URL"
      printf "Options:\\n"
      printf "  --name=HANDLE     pick the leaderboard handle (default: slugified \\\$USER)\\n"
      printf "  --join=CODE       join code for servers that gate new handles\\n"
      printf "  --company=DOMAIN  company affiliation shown on the leaderboard (e.g. anara.com)\\n"
      printf "  -h, --help        this message\\n"
      printf "\\nEnvironment overrides:\\n"
      printf "  TOKENLEADER_USER      same as --name (lower priority than the flag)\\n"
      printf "  TOKENLEADER_JOIN      same as --join (lower priority than the flag)\\n"
      printf "  TOKENLEADER_COMPANY   same as --company (lower priority than the flag)\\n"
      exit 0
      ;;
    *) printf "Unknown argument: %s\\nRun with --help for usage.\\n" "\$1" >&2; exit 1 ;;
  esac
  shift
done

# Join code: flag wins over env. Written into the LaunchAgent plist below
# so the daemon can present it on its first claim of a new handle.
JOIN_CODE="\${ARG_JOIN:-\${TOKENLEADER_JOIN:-}}"

# Company affiliation: flag wins over env. Written into the plist below;
# sent raw by the daemon — the SERVER normalizes (lowercase bare hostname)
# and ignores invalid values.
COMPANY="\${ARG_COMPANY:-\${TOKENLEADER_COMPANY:-}}"

# --- spinner + step line --------------------------------------------------
# Each step renders on one line rewritten via \\r; finish redraws with ✓/✗.
SPINNER_PID=""

cleanup_spinner() {
  if [ -n "\$SPINNER_PID" ] && kill -0 "\$SPINNER_PID" 2>/dev/null; then
    kill "\$SPINNER_PID" 2>/dev/null || true
    wait "\$SPINNER_PID" 2>/dev/null || true
  fi
  SPINNER_PID=""
}

# Always reap the spinner on exit, even on Ctrl-C / unexpected failure.
trap 'cleanup_spinner; tput cnorm 2>/dev/null || true' EXIT INT TERM

step_start() {
  # step_start <n> <label>
  CUR_STEP_N="\$1"
  CUR_STEP_LABEL="\$2"
  if [ -t 1 ]; then
    tput civis 2>/dev/null || true
    (
      local frames='⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏'
      local i=0
      while :; do
        local frame="\${frames:\$i:1}"
        printf "\\r  %s[%d/%d]%s %s %s…………%s %s%s%s" \\
          "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
          "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
          "\$C_CYAN" "\$frame" "\$C_RESET"
        i=\$(( (i + 1) % 10 ))
        sleep 0.08
      done
    ) &
    SPINNER_PID=\$!
    disown "\$SPINNER_PID" 2>/dev/null || true
  else
    # Non-TTY: just print the step opening line once.
    printf "  [%d/%d] %s … " "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$CUR_STEP_LABEL"
  fi
}

step_ok() {
  # step_ok [optional-trailing-note]
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[%d/%d]%s %s %s…………%s %s✓%s" \\
      "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
      "\$C_GREEN" "\$C_RESET"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then
      printf "  %s%s%s" "\$C_DIM" "\$1" "\$C_RESET"
    fi
    printf "\\n"
  else
    printf "ok"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then printf " (%s)" "\$1"; fi
    printf "\\n"
  fi
}

step_warn() {
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[%d/%d]%s %s %s…………%s %s!%s" \\
      "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
      "\$C_YELLOW" "\$C_RESET"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then
      printf "  %s%s%s" "\$C_YELLOW" "\$1" "\$C_RESET"
    fi
    printf "\\n"
  else
    printf "warn"
    if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then printf " (%s)" "\$1"; fi
    printf "\\n"
  fi
}

step_fail() {
  # step_fail <hint-line>
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[%d/%d]%s %s %s…………%s %s✗%s\\n" \\
      "\$C_BOLD" "\$CUR_STEP_N" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$CUR_STEP_LABEL" "\$C_DIM" "\$C_RESET" \\
      "\$C_RED" "\$C_RESET"
  else
    printf "fail\\n"
  fi
  if [ "\$#" -gt 0 ] && [ -n "\$1" ]; then
    printf "        %s↳ %s%s\\n" "\$C_RED" "\$1" "\$C_RESET" >&2
  fi
  exit 1
}

# --- step 3: prepare binary -----------------------------------------------
# bun --compile already ad-hoc signs the binary; re-signing trips macOS
# strict validation. Only strip the quarantine xattr.
do_codesign() {
  step_start 3 "Preparing binary"
  xattr -cr "\$BIN_DST" 2>/dev/null || true
  step_ok
}

# --- step 4: launchagent --------------------------------------------------
write_plist_and_register() {
  step_start 4 "Registering LaunchAgent"

  # A reinstall must honor THIS server's URL: drop any daemon-written
  # endpoint override. The state dir (TOFU secret) survives reinstalls.
  rm -f "\$STATE_DIR/endpoint"

  # Optional join code → daemon env; entry exists only when provided.
  # plutil -lint below catches XML-special characters in a code.
  JOIN_PLIST_ENTRY=""
  if [ -n "\$JOIN_CODE" ]; then
    JOIN_PLIST_ENTRY="
        <key>TOKENLEADER_JOIN</key>
        <string>\$JOIN_CODE</string>"
  fi

  # Optional company affiliation → daemon env; same conditional-entry shape
  # as the join code, with the same plutil -lint backstop for XML specials.
  COMPANY_PLIST_ENTRY=""
  if [ -n "\$COMPANY" ]; then
    COMPANY_PLIST_ENTRY="
        <key>TOKENLEADER_COMPANY</key>
        <string>\$COMPANY</string>"
  fi

  cat >"\$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>Program</key>
    <string>\${HOME}/.local/bin/anara-leaderboard</string>
    <key>ProgramArguments</key>
    <array>
        <string>\${HOME}/.local/bin/anara-leaderboard</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>TOKENLEADER_USER</key>
        <string>\${USER_NAME}</string>
        <key>TOKENLEADER_ENDPOINT</key>
        <string>\${SERVER_URL}</string>
        <key>TOKENLEADER_HOME</key>
        <string>\${HOME}/.local/share/anara-leaderboard</string>\${JOIN_PLIST_ENTRY}\${COMPANY_PLIST_ENTRY}
        <key>HOME</key>
        <string>\${HOME}</string>
        <key>PATH</key>
        <string>\${HOME}/.local/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <dict>
        <key>Crashed</key>
        <true/>
        <key>SuccessfulExit</key>
        <false/>
    </dict>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>ProcessType</key>
    <string>Background</string>
    <key>StandardOutPath</key>
    <string>\${HOME}/Library/Logs/anara-leaderboard/stdout.log</string>
    <key>StandardErrorPath</key>
    <string>\${HOME}/Library/Logs/anara-leaderboard/stderr.log</string>
    <key>WorkingDirectory</key>
    <string>\${HOME}</string>
</dict>
</plist>
PLIST_EOF
  chmod 600 "\$PLIST"
  if ! plutil -lint "\$PLIST" >/dev/null 2>&1; then
    step_fail "generated plist failed plutil -lint (see \$PLIST)"
  fi

  # launchctl bootout is ASYNC: bootstrapping too soon fails with "service
  # already loaded". Wait for the old instance to disappear, then bootstrap
  # with retries.
  launchctl bootout "\$DOMAIN/\$LABEL" 2>/dev/null || true
  for _i in 1 2 3 4 5 6 7 8 9 10; do
    launchctl print "\$DOMAIN/\$LABEL" >/dev/null 2>&1 || break
    sleep 0.5
  done
  launchctl enable "\$DOMAIN/\$LABEL" 2>/dev/null || true
  _bootstrapped=""
  for _i in 1 2 3 4 5; do
    if launchctl bootstrap "\$DOMAIN" "\$PLIST" 2>/dev/null; then _bootstrapped=1; break; fi
    sleep 1
  done
  if [ -z "\$_bootstrapped" ]; then
    step_fail "launchctl bootstrap failed (run 'launchctl bootstrap \$DOMAIN \$PLIST' for the error)"
  fi
  launchctl kickstart -k "\$DOMAIN/\$LABEL" >/dev/null 2>&1 || true
  step_ok
}

# --- step 5: start daemon -------------------------------------------------
# Don't block on "tick_done" — a first sync can take 10-60s on big
# histories. Confirm the process is running; sync continues in background.
wait_for_first_tick() {
  step_start 5 "Starting daemon"
  launchctl kickstart -k "\$DOMAIN/\$LABEL" >/dev/null 2>&1 || true

  local deadline=\$(( \$(date +%s) + 5 ))
  local state=""
  while [ "\$(date +%s)" -lt "\$deadline" ]; do
    state="\$(launchctl print "\$DOMAIN/\$LABEL" 2>/dev/null | awk -F'= *' '/^[[:space:]]*state /{print \$2; exit}' | tr -d ' ')"
    if [ "\$state" = "running" ]; then
      step_ok "running (first sync in progress in background)"
      return 0
    fi
    sleep 0.25
  done

  # Not running yet — peek at the launchd state for context but don't fail.
  state="\${state:-spawn-pending}"
  step_warn "daemon state: \$state (it'll keep retrying; check logs at \$STDERR_LOG)"
}

# Ping /stats/admin to confirm the server saw our handle. Non-fatal.
verify_on_server() {
  local body
  body="\$(curl -fsS --max-time 5 "\$SERVER_URL/stats/admin" 2>/dev/null || true)"
  if [ -z "\$body" ]; then
    printf "        %s↳ server check skipped (couldn't reach %s)%s\\n" \\
      "\$C_DIM" "\$SERVER_URL/stats/admin" "\$C_RESET"
    return 0
  fi
  # Cheap substring match for the username; avoids a JSON parser dep.
  if printf "%s" "\$body" | grep -q "\\\"user\\\":\\\"\$USER_NAME\\\""; then
    printf "        %s↳ %sserver saw your batch%s%s\\n" \\
      "\$C_DIM" "\$C_GREEN" "\$C_RESET" "\$C_DIM"
  else
    printf "        %s↳ server reachable; your batch hasn't landed yet%s\\n" \\
      "\$C_DIM" "\$C_RESET"
  fi
}

# --- summary --------------------------------------------------------------
print_summary() {
  printf "\\n%s\\n\\n" "\$DIVIDER"
  printf "  %sinstalled as%s     %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$USER_NAME" "\$C_RESET"
  printf "  %sendpoint%s         %s%s%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
  printf "  %slogs%s             %s~/Library/Logs/anara-leaderboard/stderr.log%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$C_RESET"
  printf "  %suninstall%s        %scurl -fsSL %s/uninstall | bash%s\\n" \\
    "\$C_DIM" "\$C_RESET" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
  printf "\\n  %sYour usage will appear on the leaderboard within a minute.%s\\n\\n" \\
    "\$C_GREEN" "\$C_RESET"
}

# --- ensure dirs exist before any step touches them -----------------------
ensure_dirs() {
  mkdir -p "\$HOME/.local/bin" \\
           "\$HOME/Library/LaunchAgents" \\
           "\$LOG_DIR" \\
           "\$STATE_DIR"
}
`;
}

/**
 * Installer that downloads the binary from the server's own BinaryMirror
 * cache — the server is the single network dep for install, ingest and
 * auto-update. The sha256 check is transport integrity only: manifest and
 * binary come from the same server.
 */
export function renderInstallScript(serverUrl: string, opts: InstallScriptOpts = {}): string {
  const url = trimTrailingSlash(serverUrl);
  // Surface a missing join code before doing any work; existing handles
  // reinstall fine without one (their TOFU secret rules).
  const joinWarning = opts.joinRequired
    ? `if [ -z "\$JOIN_CODE" ]; then
  printf "  %s!%s this server requires a join code for NEW handles; without one the daemon's first sync will 403.\\n" "\$C_YELLOW" "\$C_RESET"
  printf "    re-run with: %scurl -fsSL %s/install | bash -s -- --join=<code>%s\\n\\n" "\$C_BOLD" "\$SERVER_URL" "\$C_RESET"
fi
`
    : "";
  return `${renderSharedBashPreamble(url, opts)}
# Dev/staging escape hatch; default is the server's own /bin route.
BINARY_BASE_URL="\${TOKENLEADER_BINARY_URL:-\$SERVER_URL/bin}"

# --- step 2: download binary ----------------------------------------------
# manifest.json first so the binary sha256 is verified before the swap.
# Both 503 until the server's first successful mirror tick.
do_download() {
  step_start 2 "Downloading daemon binary"
  local tmp_bin="\$BIN_DST.tmp.\$\$"
  local tmp_manifest="\$BIN_DST.manifest.\$\$.json"
  local arch_asset="anara-leaderboard-\$ARCH_PATH"

  if ! curl -fsSL --max-time 30 "\$SERVER_URL/manifest.json" -o "\$tmp_manifest"; then
    rm -f "\$tmp_manifest"
    step_fail "couldn't fetch \$SERVER_URL/manifest.json (the server 503s until its binary mirror has fetched a release)"
  fi

  # No jq dep: python3 ships on every supported macOS; sed is the fallback.
  local expected_sha=""
  if command -v python3 >/dev/null 2>&1; then
    expected_sha="\$(python3 -c "import json,sys; m=json.load(open(sys.argv[1])); print(m[sys.argv[2]]['sha256'])" "\$tmp_manifest" "\$ARCH_PATH" 2>/dev/null || true)"
  fi
  if [ -z "\$expected_sha" ]; then
    # BSD-sed-compatible: collapse to one line, extract our arch's sha256.
    expected_sha="\$(tr -d '\\n\\r' < "\$tmp_manifest" \\
      | sed -E "s/.*\\"\$ARCH_PATH\\"[^}]*\\"sha256\\":\\"([0-9a-fA-F]{64})\\".*/\\1/" \\
      | grep -E '^[0-9a-fA-F]{64}\$' || true)"
  fi
  if [ -z "\$expected_sha" ]; then
    rm -f "\$tmp_manifest"
    step_fail "couldn't parse sha256 for \$ARCH_PATH out of manifest.json"
  fi

  # Stop the spinner before curl draws its own progress bar.
  cleanup_spinner
  if [ -t 1 ]; then
    tput cnorm 2>/dev/null || true
    printf "\\r\\033[K  %s[2/%d]%s Downloading daemon binary  %s↓%s\\n" \\
      "\$C_BOLD" "\$TOTAL_STEPS" "\$C_RESET" "\$C_DIM" "\$C_RESET"
  fi
  # curl -# = built-in progress bar; -f = fail on 4xx/5xx; -L = follow redirects.
  local bin_url="\$BINARY_BASE_URL/\$arch_asset"
  if ! curl -#fL "\$bin_url" -o "\$tmp_bin"; then
    rm -f "\$tmp_bin" "\$tmp_manifest"
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloading daemon binary"
    step_fail "download failed from \$bin_url (is the server reachable?)"
  fi

  local actual_sha
  actual_sha="\$(shasum -a 256 "\$tmp_bin" | awk '{print \$1}')"
  if [ "\$actual_sha" != "\$expected_sha" ]; then
    rm -f "\$tmp_bin" "\$tmp_manifest"
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloading daemon binary"
    step_fail "sha256 mismatch on \$arch_asset (expected \$expected_sha, got \$actual_sha)"
  fi

  chmod +x "\$tmp_bin"
  mv -f "\$tmp_bin" "\$BIN_DST"
  rm -f "\$tmp_manifest"

  # curl's bar left the cursor on a fresh line; emit the success line.
  if [ -t 1 ]; then
    CUR_STEP_N=2
    CUR_STEP_LABEL="Downloaded daemon binary"
    printf "  %s[2/%d]%s Downloaded daemon binary  %s…………%s %s✓%s\\n" \\
      "\$C_BOLD" "\$TOTAL_STEPS" "\$C_RESET" \\
      "\$C_DIM" "\$C_RESET" "\$C_GREEN" "\$C_RESET"
  else
    printf "  [2/%d] downloaded\\n" "\$TOTAL_STEPS"
  fi
}

# --- main -----------------------------------------------------------------
resolve_handle
print_banner
${joinWarning}ensure_dirs
do_download
do_codesign
write_plist_and_register
wait_for_first_tick
print_summary
`;
}

export function renderUninstallScript(serverUrl: string): string {
  const url = trimTrailingSlash(serverUrl);
  return `#!/usr/bin/env bash
# tokenleader self-serve uninstaller.
# Generated by the tokenleader server at ${url}.
set -euo pipefail

SERVER_URL="\${TOKENLEADER_INSTALL_URL:-${url}}"

# --- color setup ----------------------------------------------------------
if [ -t 1 ]; then
  C_RESET=$'\\033[0m'
  C_BOLD=$'\\033[1m'
  C_DIM=$'\\033[2m'
  C_GREEN=$'\\033[0;32m'
  C_YELLOW=$'\\033[0;33m'
  C_RED=$'\\033[0;31m'
else
  C_RESET=""; C_BOLD=""; C_DIM=""
  C_GREEN=""; C_YELLOW=""; C_RED=""
fi
info() { printf "  %s→%s %s\\n" "\$C_DIM" "\$C_RESET" "\$*"; }
ok()   { printf "  %s✓%s %s\\n" "\$C_GREEN" "\$C_RESET" "\$*"; }
warn() { printf "  %s!%s %s\\n" "\$C_YELLOW" "\$C_RESET" "\$*" >&2; }
err()  { printf "  %s✗%s %s\\n" "\$C_RED" "\$C_RESET" "\$*" >&2; }

if [ "\$(uname -s)" != "Darwin" ]; then
  err "This uninstaller only supports macOS."
  exit 1
fi

# Reopen stdin from the tty when piped through bash.
if [ ! -t 0 ] && [ -r /dev/tty ]; then
  exec </dev/tty
fi

printf "\\n  %stokenleader uninstaller%s\\n\\n" "\$C_BOLD" "\$C_RESET"

LABEL="${LABEL}"
DOMAIN="gui/\$(id -u)"
PLIST="\$HOME/Library/LaunchAgents/\${LABEL}.plist"
BIN="\$HOME/.local/bin/anara-leaderboard"
STATE_DIR="\$HOME/.local/share/anara-leaderboard"
LOG_DIR="\$HOME/Library/Logs/anara-leaderboard"
SECRET_FILE="\$STATE_DIR/secret"

# --- notify the server BEFORE we delete local state ------------------------
# The plist (handle) and secret file must still be on disk to authenticate
# the POST. A server outage MUST NOT block local cleanup. The handle is read
# from the plist so custom --name handles still get reported.
notify_server_uninstall() {
  local handle=""
  if [ -f "\$PLIST" ]; then
    handle="\$(/usr/libexec/PlistBuddy -c 'Print :EnvironmentVariables:TOKENLEADER_USER' "\$PLIST" 2>/dev/null || true)"
  fi
  if [ -z "\$handle" ] && [ -f "\$PLIST" ]; then
    # PlistBuddy ships with macOS; this awk fallback costs nothing.
    handle="\$(awk '/<key>TOKENLEADER_USER<\\/key>/{getline; gsub(/.*<string>|<\\/string>.*/, ""); print; exit}' "\$PLIST" 2>/dev/null || true)"
  fi
  local secret=""
  if [ -r "\$SECRET_FILE" ]; then
    secret="\$(tr -d '[:space:]' < "\$SECRET_FILE" 2>/dev/null || true)"
  fi
  if [ -z "\$handle" ] || [ -z "\$secret" ]; then
    info "Skipping server notify (handle/secret not on disk)."
    return 0
  fi
  info "Notifying server of uninstall for \$handle..."
  local body
  body="\$(printf '{"user":"%s"}' "\$handle")"
  if curl --max-time 5 --fail-with-body -sS \\
       -H "Content-Type: application/json" \\
       -H "X-Tokenleader-Secret: \$secret" \\
       -X POST "\$SERVER_URL/events/uninstall" \\
       --data "\$body" >/dev/null 2>&1; then
    ok "Server acknowledged."
  else
    warn "Server notify failed (continuing with local cleanup)."
  fi
}
notify_server_uninstall

info "Stopping LaunchAgent (if running)..."
if launchctl bootout "\$DOMAIN/\$LABEL" 2>/dev/null; then
  ok  "Booted out \$LABEL."
else
  warn "\$LABEL was not loaded (or bootout failed); continuing."
fi

if [ -f "\$PLIST" ]; then
  rm -f "\$PLIST"
  ok "Removed \$PLIST"
else
  info "No plist at \$PLIST"
fi

if [ -f "\$BIN" ]; then
  rm -f "\$BIN"
  ok "Removed \$BIN"
else
  info "No binary at \$BIN"
fi

ANSWER="\${TOKENLEADER_PURGE:-}"
if [ -z "\$ANSWER" ]; then
  printf "\\n  Also delete daemon state %s%s%s and logs %s%s%s? [y/N] " \\
    "\$C_BOLD" "\$STATE_DIR" "\$C_RESET" \\
    "\$C_BOLD" "\$LOG_DIR" "\$C_RESET"
  read -r ANSWER || ANSWER=""
fi
case "\$ANSWER" in
  y|Y|yes|YES)
    rm -rf "\$STATE_DIR" "\$LOG_DIR"
    ok "Removed state and logs."
    ;;
  *)
    # The endpoint override is server-instance-specific; only the TOFU
    # secret is worth preserving across installs.
    rm -f "\$STATE_DIR/endpoint"
    info "Keeping \$STATE_DIR and \$LOG_DIR."
    ;;
esac

printf "\\n  %s✓ uninstall complete.%s\\n\\n" "\$C_GREEN" "\$C_RESET"
`;
}

// scripts/install.sh keeps its own copy of this preamble (it is NOT sourced
// from here); this export exists for tests/tooling.
export { renderSharedBashPreamble };
